export const CATEGORY_COLORS = [
  '#D14B61',
  '#F27C66',
  '#F2B872',
  '#D7C44C',
  '#1D9B5F',
  '#39B980',
  '#2D9CDB',
  '#4E7BF2',
  '#7B61FF',
  '#B05CF6',
  '#F46AB9',
  '#6B7280',
];

export const CATEGORY_ICON_OPTIONS = [
  'cart-outline',
  'silverware-fork-knife',
  'coffee-outline',
  'bus',
  'gas-station-outline',
  'home-outline',
  'lightning-bolt-outline',
  'cellphone',
  'credit-card-outline',
  'heart-pulse',
  'shield-check-outline',
  'shopping-outline',
  'movie-open-outline',
  'airplane',
  'school-outline',
  'gift-outline',
  'cash',
  'cash-plus',
  'laptop',
  'chart-line',
  'tag-outline',
];
